spring:
  application:
    name: spring-reactive
  r2dbc:
    url: r2dbc:postgresql://neondb_owner:VJ7hPGb0MtiU@ep-winter-night-a1j2mbco.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: VJ7hPGb0MtiU
    show-sql: true

gemini:
  api:
    key: tu_api_key_aqui
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent
